import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>fooDAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center font-extralight">fooDAO</h1>
      </main>
    </div>
  );
}
