version: "3"

services:
  server:
    build:
      context: ../src
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
    - ../src:/go/src/github.com/kuma0328/web3hackathon
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
